name: Angular CI/CD Pipeline
on:
  push:
    branches: [ master]
jobs:
  build:
    runs-on: windows-latest
    name: Build Angular + .NET
    env:
     ANGULAR_PROJECT_PATH: ./management-agular
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm ci
    - name: Run Angular tests
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm run test -- --watch=false --browsers=ChromeHeadless
    - name: Build Angular
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm run build -- --configuration production
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: angular-dist
        path: dist/
