name: Angular CI/CD Pipeline
on:
  push:
    branches: [ master]
jobs:
  build:
    runs-on: windows-latest
    name: Build Angular + .NET
    env:
     ANGULAR_PROJECT_PATH: Shubhankarodi/management-ngrx
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm ci
    - name: Build Angular
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm run build -- --configuration production
    - name: Run tests (optional)
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm test -- --watch=false --browsers=ChromeHeadless
